### ISSUE TITLE
loading window has a vertical scroll bar on Windows

### ISSUE THREAD

**Issue by tylerlong** [tylerlong/oxford-learners-dictionaries#4]

**Comment by tylerlong** [comment]
```css
html, body {
    overflow: hidden;
}
```
